const productos = [
    {
    id: 1,
    mane: 'Difusor cristal',
    image: './imagenes/difusores.jpg' ,
    precio: 1500,
    stock: 10,
    },
    {id: 2,
        mane: "Difusor cristal",
        image: "./imagenes/difusores.jpg" ,
        precio: 1500,
        stock: 20,
    },
    {id: 3,
        mane: "Difusor cristal",
        image: "./imagenes/difusores.jpg" ,
        precio: 1500,
        stock: 15,
    },
    {id: 4,
        mane: "Difusor cristal",
        image: "./imagenes/difusores.jpg" ,
        precio: 1500,
        stock: 15,
    },
    {id: 5,
        mane: "Difusor cristal",
        image: "" ,
        precio: 1500,
        stock: 20,
    },
    {id: 6,
        mane: "Difusor cristal",
        image: "" ,
        precio: 1500,
        stock: 10,
    }
]   

export default productos;