const productos = [
    {
    id: 1,
    name: 'Velas glass',
    image: './imagenes/Velas de soja.jpg' ,
    descripcion: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.Quae ducimus perspiciatis unde minus quam iste molestias est dolor",
    precio: 1500,
    categoryId: "velas",
    stock: 10,
    },
    {id: 2,
        name: "Velas cuenco ",
        image: "./imagenes/difusores.jpg" ,
        descripcion: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.Quae ducimus perspiciatis unde minus quam iste molestias est dolor",
        precio: 1500,
        categoryId: "velas",
        stock: 20,
    },
    {id: 3,
        name: "Difusor cristal",
        image: "./imagenes/difusores.jpg" ,
        descripcion: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.Quae ducimus perspiciatis unde minus quam iste molestias est dolor",
        precio: 1500,
        categoryId: "difusores",
        stock: 15,
    },
    {id: 4,
        name: "Difusor nature",
        image: "./imagenes/difusores.jpg" ,
        descripcion: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.Quae ducimus perspiciatis unde minus quam iste molestias est dolor",
        precio: 1500,
        categoryId: "difusores",
        stock: 15,
    },
    {id: 5,
        name: "Esencia de vainilla",
        image: "./imagenes/difusores.jpg", 
        descripcion: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.Quae ducimus perspiciatis unde minus quam iste molestias est dolor",
        precio: 1500,
        categoryId: "esencias",
        stock: 20,
    },
    {id: 6,
        name: "Esencia de verbena",
        image: "./imagenes/difusores.jpg" ,
        descripcion: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.Quae ducimus perspiciatis unde minus quam iste molestias est dolor",
        precio: 1500,
        categoryId: `esencias`,
        stock: 10,
    }
]   

export default productos;